### ISSUE TITLE
Building is bugged

### ISSUE THREAD

**Issue by Xaocsoul** [ObvilionNetwork/mindustry-hub-plugin#10]
Sorry for bugging you again when ever you try to build it just spams console with errors even when configed on admin

**Comment by Fatonndev** [comment]
Send logs with errors

**Comment by Xaocsoul** [comment]
[log-2.txt](https://github.com/ObvilionNetwork/mindustry-hub-plugin/files/11357846/log-2.txt)

**Comment by Fatonndev** [comment]
You haven't updated the config. Delete the `config.properties` file and start the server.

**Comment by Xaocsoul** [comment]
I did update it I completely deleted all the files for the mod before putting the new version on the server

**Comment by Xaocsoul** [comment]
I don’t know how they would still be there I know I deleted em

**Comment by Fatonndev** [comment]
Fixed. Please, check last release
