### ISSUE TITLE
error in the number of players

### ISSUE THREAD

**Issue by DikHalz** [ObvilionNetwork/mindustry-hub-plugin#6]
![image](https://user-images.githubusercontent.com/87813567/206600689-6969f51c-a174-48ab-8185-8a85c3af6442.png)
The number of connected players doubles to infinity, there were only 3 players online at the time.

**Comment by Fatonndev** [comment]
Hi! You may be using an older version of the plugin. Please send the version of the installed Oblivion Hub plugin. To find out the version, you can enter the command `hub version`

**Comment by DikHalz** [comment]
Thanks for answering... The version I use is the latest one in release

![image](https://user-images.githubusercontent.com/87813567/206811702-c4f64746-00fc-47a4-b043-8065de957448.png)

**Comment by Fatonndev** [comment]
I think this may be due to the fact that you specified the hub server in the plugin config, which causes recursion. If this is not the case, please write here.

**Comment by Fatonndev** [comment]
I have released an update that protects the hub from recursively adding online [here](https://github.com/ObvilionNetwork/mindustry-hub-plugin/releases/tag/0.5) and a usage example you can find 
[here](https://github.com/ObvilionNetwork/mindustry-hub-plugin/blob/b3bbacfd59289c4e645f0cc5d699e7e48d56041e/src/main/resources/servers.properties#L36)

**Comment by DikHalz** [comment]
> 

Oh sure, why didn't I think of that before haha... Sorry for the inconvenience, that solves everything, had the Hub IP added in another line... rookie mistake, thanks for the support

**Comment by Fatonndev** [comment]
Thank you for contacting us
