### ISSUE TITLE
Incompatible with new version 142

### ISSUE THREAD

**Issue by DikHalz** [ObvilionNetwork/mindustry-hub-plugin#7]

**Comment by DikHalz** [comment]
the new update broke several plugins

**Comment by Fatonndev** [comment]
Hello, please pin the server log with an error 🙂 

Best regards, Daniel from obvilion.ru team.

**Comment by DikHalz** [comment]
No error appears, the server opens without problems, it recognizes the mod but everything else is as if it did not exist

**Comment by DikHalz** [comment]
Someone opened PR with the solution

**Comment by Fatonndev** [comment]
Open PR #8 is not the solution to the problem.
