### ISSUE TITLE
How do you make it so normal people can build

### ISSUE THREAD

**Issue by Xaocsoul** [ObvilionNetwork/mindustry-hub-plugin#9]
I have an rp server that uses this to connect to other servers but I can't figure out how to let them build

**Comment by Fatonndev** [comment]
Check v0.6 release. I added new property in `config.properties`, where you can find `canBuild` property.
![image](https://user-images.githubusercontent.com/56699208/233331374-4ea7b388-2b58-42b3-9844-d27c5bce9d42.png)
